Numpy arrays are simmilar to lists in Python, but they are more efficient for numerical operations. They can only hold  one data type and they are stored in contiguous memory locations.

In [219]:
import numpy as np

In [220]:
my_list = [1, 2, 3, 4, 5]

my_array = np.array(my_list)

type(my_array)

numpy.ndarray

This is a 1-dimensional array.

For a 2-dimensional array, we use a list of lists:

In [221]:
second_list = [6, 7, 8, 9, 10]
two_d_array = np.array([my_list, second_list])
print(two_d_array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


An ndarray is defined by the number of dimensions (ndim) and the shape (size of each dimension).


In [222]:
two_d_array.shape

(2, 5)

You can check the total number of elements in an ndarray using the size attribute:

In [223]:
two_d_array.size

10

You can check the type of data held in the array with the .dtype attribute:

In [224]:
two_d_array.dtype

dtype('int64')

Numpy has a variety of functions to create arrays. Here are a few examples:

In [225]:
#np.identity()  creates a square 2d array with ones on the diagonal

np.identity(n = 3)  # Size of the array



array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [226]:
#np.ones() creates an array filled with ones

np.ones(shape=(3, 3))  # Size of the array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [227]:
#np.zeros() creates an array filled with zeros

np.zeros(shape=(3, 3))  # Size of the array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Numpy ndarrays offer numbed indexing and slicing syntax that mirrors syntax for lists.


In [228]:
one_d_array = np.array([1, 2, 3, 4, 5])

one_d_array[3] # Get item at index 3

4

In [229]:
one_d_array[::-1] # Slicing the array in reverse order

array([5, 4, 3, 2, 1])

In [230]:
# Create new 2d array  
two_d_array = np.array([one_d_array, one_d_array + 6, one_d_array + 12])

print(two_d_array)

[[ 1  2  3  4  5]
 [ 7  8  9 10 11]
 [13 14 15 16 17]]


In [231]:
# Get the element at row 2, column 3

two_d_array[2, 3]

16

In [234]:
# Slice elements starting at row 2, and column 5

two_d_array[1:, 4:]

array([[11],
       [17]])

In [235]:
# Reverse both dimensions of the array

two_d_array[::-1, ::-1]

array([[17, 16, 15, 14, 13],
       [11, 10,  9,  8,  7],
       [ 5,  4,  3,  2,  1]])

Numpy has a variety of built in functions to manipulate arrays. Here are a few examples:

In [237]:
np.reshape(a=two_d_array, newshape=(5,3)) #reshape the array into a 5x3 matrix

array([[ 1,  2,  3],
       [ 4,  5,  7],
       [ 8,  9, 10],
       [11, 13, 14],
       [15, 16, 17]])

In [238]:
np.ravel(a=two_d_array, order='C') # flatten the array using C style (by row major order)

array([ 1,  2,  3,  4,  5,  7,  8,  9, 10, 11, 13, 14, 15, 16, 17])

In [239]:
np.ravel(a=two_d_array, order='F') # flatten the array using Fortran style (by column major order)  

array([ 1,  7, 13,  2,  8, 14,  3,  9, 15,  4, 10, 16,  5, 11, 17])

In [240]:
two_d_array.flatten() # flatten the array using C style (by row major order)

array([ 1,  2,  3,  4,  5,  7,  8,  9, 10, 11, 13, 14, 15, 16, 17])

In [242]:
two_d_array.T # transpose the array

array([[ 1,  7, 13],
       [ 2,  8, 14],
       [ 3,  9, 15],
       [ 4, 10, 16],
       [ 5, 11, 17]])

In [243]:
np.flipud(two_d_array) # flip the array along the first axis

array([[13, 14, 15, 16, 17],
       [ 7,  8,  9, 10, 11],
       [ 1,  2,  3,  4,  5]])

In [244]:
np.fliplr(two_d_array) # flip the array along the second axis

array([[ 5,  4,  3,  2,  1],
       [11, 10,  9,  8,  7],
       [17, 16, 15, 14, 13]])

In [ ]:
np.rot90(two_d_array, k=1) # rotate the array 90 degrees counter

In [246]:
np.roll(a= two_d_array, shift = 2, axis = 1) # roll the array along the second axis by 2 positions

array([[ 4,  5,  1,  2,  3],
       [10, 11,  7,  8,  9],
       [16, 17, 13, 14, 15]])

In [252]:
array_to_join = np.array([[10,20,30],[40,50,60],[70,80,90]])

np.concatenate((two_d_array, array_to_join), axis=1) # concatenate the

array([[ 1,  2,  3,  4,  5, 10, 20, 30],
       [ 7,  8,  9, 10, 11, 40, 50, 60],
       [13, 14, 15, 16, 17, 70, 80, 90]])

ndarrays true power lies in their ability to perform complex mathematical operations on entire arrays at once.

In [253]:
two_d_array + 100 #Add 100 to each element in the array

array([[101, 102, 103, 104, 105],
       [107, 108, 109, 110, 111],
       [113, 114, 115, 116, 117]])